ARG BUILDTAG=build
FROM kube-service-selectors:${BUILDTAG}
MAINTAINER Hystax

COPY .coveragerc ./
COPY pyproject.toml ./
COPY unittest.cfg ./

COPY test-requirements.txt ./
RUN pip install --no-cache-dir -r test-requirements.txt

COPY tests ./tests
